"""Add password hash to User

Revision ID: 95c91d22ac2c
Revises: ec628709828c
Create Date: 2025-04-11 21:06:49.291080

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95c91d22ac2c"
down_revision = "ec628709828c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=256), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=256), nullable=True
        )

    # ### end Alembic commands ###
