"""Add password hash to User

Revision ID: ec628709828c
Revises: c653ca549125
Create Date: 2025-04-11 20:24:44.275447

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec628709828c"
down_revision = "c653ca549125"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
